apiVersion: helm.toolkit.fluxcd.io/v2  
kind: HelmRelease  
metadata:  
  name: v2-deploy-test
  namespace: arc-v2-runners-scaleset
spec:  
  interval: 5m  
  chart:  
    spec:  
      chart: gha-runner-scale-set  
      version: "0.14.1"  
      sourceRef:  
        kind: HelmRepository  
        name: arc-charts-v2 
        namespace: flux-system  
  install:
    createNamespace: true        
  values:
    githubConfigUrl: https://github.com/bhaskar-areti/test-githubactions-como-pricer
    githubConfigSecret: arc-github-app-v2
    runnerScaleSetName: v2-deploy-test
    labels:
      arc: v2-deploy-test
    minRunners: 0
    maxRunners: 5
    runner:
      image:
        repository: ghcr.io/actions/actions-runner
        tag: latest
    webhookServer:
      enabled: true
      service:
        type: LoadBalancer

